# Generated by Django 5.2.12 on 2026-03-12 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tri_app', '0002_rename_roles_gameparticipant_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 16, 47, 5, 796732, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
    ]
