# Generated by Django 5.2.12 on 2026-03-12 19:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tri_app', '0003_user_is_admin_alter_notification_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.ImageField(blank=True, upload_to='characters/', verbose_name='Изображение персонажа'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 19, 50, 16, 887231, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
    ]
