# Generated by Django 5.2.12 on 2026-03-13 14:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tri_app', '0005_alter_notification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='character',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tri_app.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 14, 26, 37, 891827, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tri_app.character', verbose_name='Персонаж'),
        ),
    ]
