# Generated by Django 5.2.12 on 2026-03-05 17:05

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('about', models.TextField(blank=True, max_length=150, verbose_name='О пользователе')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('about', models.TextField(blank=True, verbose_name='О персонаже')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('characteristics', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Владелец персонажа')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название игры')),
                ('about', models.TextField(blank=True, verbose_name='Об игре')),
                ('rules', models.TextField(blank=True, verbose_name='Правила игры')),
                ('max_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Должен быть хотя бы один игрок'), django.core.validators.MaxValueValidator(100, 'В игре не может быть больше 100 игроков')], verbose_name='Количество игроков')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'Приостановлена'), ('ended', 'Завершена'), ('abandoned', 'Брошена'), ('pending', 'Ожидает начала')], default='pending', verbose_name='Статус игры')),
                ('invite_code', models.CharField(blank=True, max_length=20, verbose_name='Код для приглашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания игры')),
                ('characters', models.ManyToManyField(related_name='games', to='app.character', verbose_name='Персонажи в игре')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('gm', 'Мастер'), ('moderator', 'Модератор'), ('player', 'Игрок'), ('spectator', 'Наблюдатель')], default='player', verbose_name='Роль в игре')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения к игре')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game', verbose_name='Игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Участник игры',
                'verbose_name_plural': 'Участники игры',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='app.GameParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('about', models.TextField(blank=True, verbose_name='О предмете')),
                ('characteristics', models.TextField(blank=True, verbose_name='Характеристики')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='CharactersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charcters_items', to='app.character', verbose_name='Владелец предмета')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_items', to='app.game', verbose_name='Предмет в игре')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters_items', to='app.item', verbose_name='Этот предмет')),
            ],
            options={
                'verbose_name': 'Предмет персонажа',
                'verbose_name_plural': 'Предметы персонажа',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(related_name='characters', through='app.CharactersItem', to='app.item', verbose_name='Предметы персонажа'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('about', models.TextField(blank=True, verbose_name='О локации')),
                ('rules', models.TextField(blank=True, verbose_name='Дополнительные правила')),
                ('picture', models.ImageField(blank=True, upload_to='locations/', verbose_name='Изображение локации')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('items', models.ManyToManyField(related_name='locations', to='app.item', verbose_name='Предметы на локации')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='locations',
            field=models.ManyToManyField(related_name='games', to='app.location', verbose_name='Локации в игре'),
        ),
        migrations.AddField(
            model_name='character',
            name='at_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='app.location', verbose_name='Персонаж в локации'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4000, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app.character', verbose_name='Персонаж')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.game', verbose_name='Игра')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='app.post', verbose_name='Ответ на пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=4000, verbose_name='Содержание')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 3, 6, 17, 5, 10, 885079, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.character', verbose_name='Персонаж')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
