# Generated by Django 5.2.12 on 2026-03-06 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameparticipant',
            old_name='roles',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 7, 12, 31, 39, 275151, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
    ]
