# Generated by Django 5.2.12 on 2026-03-12 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_character_picture_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 20, 37, 28, 97652, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
    ]
