# Generated by Django 5.2.12 on 2026-03-13 14:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_notification_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 14, 28, 35, 62157, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
    ]
