# Generated by Django 5.2.12 on 2026-03-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_notification_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 18, 12, 12, 20, 316180, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
    ]
