# Generated by Django 5.2.12 on 2026-03-17 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_notification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 18, 13, 18, 31, 915749, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения'),
        ),
    ]
